### ISSUE TITLE
Add additional metadata for California samples

### ISSUE THREAD

**Issue by batson** [czbiohub/ncov#3]
**Context**  
For each California sample, we would like the following additional metadata fields. They should be available for filtering and for coloring.

**Description**   

Add ability to color by:

County
Region (defined per county in attached)
Latitude (defined per county in attached)
CA Lab (submitting lab if in CA, blank otherwise)

[ca_regions.txt](https://github.com/czbiohub/ncov/files/4773489/ca_regions.txt)

**Comment by ttung** [comment]
I think it makes more sense to wait for @phoenixAja's changes to land before we do this.

**Comment by samlhao** [comment]
The current config colors by county - I've overrided the default orderings and lat_long in order to set the default coloring scheme by latitude. Since these are continuous values, we'll need to add a separate field that binned them if we want to filter by latitude meaningfully. I'll add the county region (as a new metadata field county_region because we don't want to redefine the existing regions) and CA lab configs today.

**Comment by phoenixAja** [comment]
@samlhao can you add me as a reviewer to that PR so I can see how you did this?

**Comment by samlhao** [comment]
addressed by PR #4
